### ISSUE TITLE
acts_as_tree

### ISSUE THREAD

**Issue by wallygva** [BibApp/BibApp#10]
perhaps I'm just so new to git and ruby that it's a trivial matter but as I did a fresh install of rc3 i hit a snag where the acts_as_tree gem wasn't checking in properly--still belonged to the github host so I couldn't get the system to run.    I grabbed a version and installed it locally then tweaked the Gemfile and ran "bundle install" again and everything was OK.   But now I have an older verison of acts_as_tree so perhaps that's a problem I'll need to address.

**Comment by wijiti** [comment]
I ran into the same issue. My solution was to install the gems locally to my Bibapp application using:

bundle install --deployment

**Comment by hading** [comment]
Best to use bundler to install the gems and even better if possible to use RVM to ensure just the gems needed for Bibapp (or whatever app one is using for that matter). Bundler should be able to make sure that the right version of a gem is being used even when older (or newer) are installed.

I'm going to close this.
