### ISSUE TITLE
Slow SQL

### ISSUE THREAD

**Issue by jfurfey** [BibApp/BibApp#106]
As our installation has grown, we've noticed slower and slower response times for the show people tables.  I recently installed New Relic to try and gain some clues as to the problem.  There's one particular SQL query that really seems to bog things down.  I've attached the information below.

Anyone else having problems with this?

 SQL

SELECT `works`.\* FROM `works` INNER JOIN `contributorships` ON `works`.id = `contributorships`.work_id WHERE ((`contributorships`.person_id = ?) AND ((contributorships.contributorship_state_id = ?))) ORDER BY publication_date_year desc, publication_date_month desc, publication_date_day DESC LIMIT ?
Query analysis (show details)

Table   Hint
works  
This table was retrieved with a full table scan, which is often quite bad for performance, unless you only retrieve a few rows.
The table was retrieved with this index:
No index was used in this part of the query.
MySQL had to do an extra pass to retrieve the rows in sorted order, which is a cause of poor performance but sometimes unavoidable.
You can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.
Approximately 20541 rows of this table were scanned.
contributorships  
The table was retrieved with this index: work_person_join
You can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.
Approximately 1 row of this table was scanned.
Stack trace (hide Rails)

…lib/active_record/connection_adapters/mysql_adapter.rb: 289:in `execute'
…lib/active_record/connection_adapters/mysql_adapter.rb: 633:in`select'
…rd/connection_adapters/abstract/database_statements.rb:   7:in `select_all'
…ive_record/connection_adapters/abstract/query_cache.rb:  54:in`select_all'
…ive_record/connection_adapters/abstract/query_cache.rb:  68:in `cache_sql'
…ive_record/connection_adapters/abstract/query_cache.rb:  54:in`select_all'
…1.8/gems/activerecord-3.0.10/lib/active_record/base.rb: 473:in `find_by_sql_ActiveRecord_self_name_find_by_sql'
…gems/activerecord-3.0.10/lib/active_record/relation.rb:  64:in`to_a'
…rd-3.0.10/lib/active_record/relation/finder_methods.rb: 341:in `find_first'
…rd-3.0.10/lib/active_record/relation/finder_methods.rb: 122:in`first'
/data/rails/Bibapp/releases/20121005151608/app/views/people/_people_table.html.haml:12:in `_app_views_people__people_table_html_haml__880886778__627804028_2040896'
…gems/activerecord-3.0.10/lib/active_record/relation.rb:  13:in`each'
…gems/activerecord-3.0.10/lib/active_record/relation.rb:  13:in `__send__'
…gems/activerecord-3.0.10/lib/active_record/relation.rb:  13:in `each'
/data/rails/Bibapp/releases/20121005151608/app/views/people/_people_table.html.haml:7:in`_app_views_people__people_table_html_haml__880886778__627804028_2040896'
…1.8/gems/actionpack-3.0.10/lib/action_view/template.rb: 135:in `send'
…1.8/gems/actionpack-3.0.10/lib/action_view/template.rb: 135:in`render'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  54:in `instrument'
…1.8/gems/actionpack-3.0.10/lib/action_view/template.rb: 127:in`render'
…s/actionpack-3.0.10/lib/action_view/render/partials.rb: 333:in `render_partial'
…s/actionpack-3.0.10/lib/action_view/render/partials.rb: 262:in`render'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  52:in `instrument'
….0.10/lib/active_support/notifications/instrumenter.rb:  21:in`instrument'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  52:in `instrument'
…s/actionpack-3.0.10/lib/action_view/render/partials.rb: 260:in`render'
…s/actionpack-3.0.10/lib/action_view/render/partials.rb: 378:in `_render_partial'
…/actionpack-3.0.10/lib/action_view/render/rendering.rb:  31:in`render_without_haml'
…8/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:  11:in `render'
…ed/bundle/ruby/1.8/gems/haml-3.1.4/lib/haml/helpers.rb:  90:in`non_haml'
…8/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:  11:in `render'
/data/rails/Bibapp/releases/20121005151608/app/views/people/index.html.haml:16:in`_app_views_people_index_html_haml___196894920__627710168_0'
…8/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:  93:in `capture'
…ed/bundle/ruby/1.8/gems/haml-3.1.4/lib/haml/helpers.rb: 345:in`call'
…ed/bundle/ruby/1.8/gems/haml-3.1.4/lib/haml/helpers.rb: 345:in `capture_haml_without_haml_xss'
…ed/bundle/ruby/1.8/gems/haml-3.1.4/lib/haml/helpers.rb: 569:in`with_haml_buffer'
…ed/bundle/ruby/1.8/gems/haml-3.1.4/lib/haml/helpers.rb: 341:in `capture_haml_without_haml_xss'
…/ruby/1.8/gems/haml-3.1.4/lib/haml/helpers/xss_mods.rb:  61:in`capture_haml'
…8/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:  93:in `capture'
…ms/actionpack-3.0.10/lib/action_view/render/layouts.rb:  56:in`_layout_for'
…s/actionpack-3.0.10/lib/action_view/render/partials.rb: 334:in `render_partial'
/data/rails/Bibapp/releases/20121005151608/app/views/layouts/_main_body_no_h2.html.haml:3:in`_app_views_layouts__main_body_no_h__html_haml__544790485__624178508_2205856'
…1.8/gems/actionpack-3.0.10/lib/action_view/template.rb: 135:in `send'
…1.8/gems/actionpack-3.0.10/lib/action_view/template.rb: 135:in`render'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  54:in `instrument'
…1.8/gems/actionpack-3.0.10/lib/action_view/template.rb: 127:in`render'
…s/actionpack-3.0.10/lib/action_view/render/partials.rb: 333:in `render_partial'
…s/actionpack-3.0.10/lib/action_view/render/partials.rb: 262:in`render'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  52:in `instrument'
….0.10/lib/active_support/notifications/instrumenter.rb:  21:in`instrument'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  52:in `instrument'
…s/actionpack-3.0.10/lib/action_view/render/partials.rb: 260:in`render'
…s/actionpack-3.0.10/lib/action_view/render/partials.rb: 378:in `_render_partial'
…/actionpack-3.0.10/lib/action_view/render/rendering.rb:  20:in`render_without_haml'
…8/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:  13:in `render'
/data/rails/Bibapp/releases/20121005151608/app/views/people/index.html.haml:6:in`_app_views_people_index_html_haml___196894920__627710168_0'
…1.8/gems/actionpack-3.0.10/lib/action_view/template.rb: 135:in `send'
…1.8/gems/actionpack-3.0.10/lib/action_view/template.rb: 135:in`render'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  54:in `instrument'
…1.8/gems/actionpack-3.0.10/lib/action_view/template.rb: 127:in`render'
…/actionpack-3.0.10/lib/action_view/render/rendering.rb:  59:in `_render_template'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  52:in`instrument'
….0.10/lib/active_support/notifications/instrumenter.rb:  21:in `instrument'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  52:in`instrument'
…/actionpack-3.0.10/lib/action_view/render/rendering.rb:  56:in `_render_template'
…/actionpack-3.0.10/lib/action_view/render/rendering.rb:  26:in`render_without_haml'
…8/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:  13:in `render'
…actionpack-3.0.10/lib/abstract_controller/rendering.rb: 115:in`_render_template'
…actionpack-3.0.10/lib/abstract_controller/rendering.rb: 109:in `render_to_body'
…onpack-3.0.10/lib/action_controller/metal/renderers.rb:  47:in`render_to_body'
…ck-3.0.10/lib/action_controller/metal/compatibility.rb:  55:in `render_to_body'
…actionpack-3.0.10/lib/abstract_controller/rendering.rb: 102:in`render_to_string'
…actionpack-3.0.10/lib/abstract_controller/rendering.rb:  93:in `render'
…onpack-3.0.10/lib/action_controller/metal/rendering.rb:  17:in`render'
…-3.0.10/lib/action_controller/metal/instrumentation.rb:  40:in `render'
…upport-3.0.10/lib/active_support/core_ext/benchmark.rb:   5:in`ms'
                         /usr/lib/ruby/1.8/benchmark.rb: 308:in `realtime'
…upport-3.0.10/lib/active_support/core_ext/benchmark.rb:   5:in`ms'
…-3.0.10/lib/action_controller/metal/instrumentation.rb:  40:in `render'
…-3.0.10/lib/action_controller/metal/instrumentation.rb:  78:in`cleanup_view_runtime'
….0.10/lib/active_record/railties/controller_runtime.rb:  15:in `cleanup_view_runtime'
…-3.0.10/lib/action_controller/metal/instrumentation.rb:  39:in`render'
…-3.0.10/lib/action_controller/metal/implicit_render.rb:  10:in `default_render'
…-3.0.10/lib/action_controller/metal/implicit_render.rb:   5:in`send_action'
…gems/actionpack-3.0.10/lib/abstract_controller/base.rb: 150:in `process_action'
…onpack-3.0.10/lib/action_controller/metal/rendering.rb:  11:in`process_action'
…actionpack-3.0.10/lib/abstract_controller/callbacks.rb:  18:in `process_action'
…s/activesupport-3.0.10/lib/active_support/callbacks.rb: 461:in`_run__29468547__process_action__199225275__callbacks'
…s/activesupport-3.0.10/lib/active_support/callbacks.rb: 410:in `send'
…s/activesupport-3.0.10/lib/active_support/callbacks.rb: 410:in`_run_process_action_callbacks'
…s/activesupport-3.0.10/lib/active_support/callbacks.rb:  94:in `send'
…s/activesupport-3.0.10/lib/active_support/callbacks.rb:  94:in`run_callbacks'
…actionpack-3.0.10/lib/abstract_controller/callbacks.rb:  17:in `process_action'
…ctionpack-3.0.10/lib/action_controller/metal/rescue.rb:  17:in`process_action'
…-3.0.10/lib/action_controller/metal/instrumentation.rb:  30:in `process_action'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  52:in`instrument'
….0.10/lib/active_support/notifications/instrumenter.rb:  21:in `instrument'
…tivesupport-3.0.10/lib/active_support/notifications.rb:  52:in`instrument'
…-3.0.10/lib/action_controller/metal/instrumentation.rb:  29:in `process_action'
…gems/actionpack-3.0.10/lib/abstract_controller/base.rb: 119:in`process'
…actionpack-3.0.10/lib/abstract_controller/rendering.rb:  41:in `process'
…/gems/actionpack-3.0.10/lib/action_controller/metal.rb: 138:in`dispatch'
…-3.0.10/lib/action_controller/metal/rack_delegation.rb:  14:in `dispatch'
…/gems/actionpack-3.0.10/lib/action_controller/metal.rb: 178:in`action'
…onpack-3.0.10/lib/action_dispatch/routing/route_set.rb:  62:in `call'
…onpack-3.0.10/lib/action_dispatch/routing/route_set.rb:  62:in`dispatch'
…onpack-3.0.10/lib/action_dispatch/routing/route_set.rb:  27:in `call'
…1.8/gems/rack-mount-0.6.14/lib/rack/mount/route_set.rb: 148:in`call'
…ms/rack-mount-0.6.14/lib/rack/mount/code_generation.rb:  93:in `recognize'
…ms/rack-mount-0.6.14/lib/rack/mount/code_generation.rb: 285:in`optimized_each'
…ms/rack-mount-0.6.14/lib/rack/mount/code_generation.rb:  92:in `recognize'
…1.8/gems/rack-mount-0.6.14/lib/rack/mount/route_set.rb: 139:in`call'
…onpack-3.0.10/lib/action_dispatch/routing/route_set.rb: 493:in `call'
…le/ruby/1.8/gems/oa-core-0.3.2/lib/omniauth/builder.rb:  30:in`call'
…b/action_dispatch/middleware/best_standards_support.rb:  17:in `call'
…tionpack-3.0.10/lib/action_dispatch/middleware/head.rb:  14:in`call'
…le/ruby/1.8/gems/rack-1.2.5/lib/rack/methodoverride.rb:  24:in `call'
…3.0.10/lib/action_dispatch/middleware/params_parser.rb:  21:in`call'
…ionpack-3.0.10/lib/action_dispatch/middleware/flash.rb: 182:in `call'
…b/action_dispatch/middleware/session/abstract_store.rb: 149:in`call'
…npack-3.0.10/lib/action_dispatch/middleware/cookies.rb: 302:in `call'
…s/activerecord-3.0.10/lib/active_record/query_cache.rb:  32:in`call'
…ive_record/connection_adapters/abstract/query_cache.rb:  28:in `cache'
…s/activerecord-3.0.10/lib/active_record/query_cache.rb:  12:in`cache'
…s/activerecord-3.0.10/lib/active_record/query_cache.rb:  31:in `call'
…record/connection_adapters/abstract/connection_pool.rb: 354:in`call'
…ack-3.0.10/lib/action_dispatch/middleware/callbacks.rb:  46:in `call'
…s/activesupport-3.0.10/lib/active_support/callbacks.rb: 416:in`_run_call_callbacks'
…ack-3.0.10/lib/action_dispatch/middleware/callbacks.rb:  44:in `call'
…d/bundle/ruby/1.8/gems/rack-1.2.5/lib/rack/sendfile.rb: 106:in`call'
…ack-3.0.10/lib/action_dispatch/middleware/remote_ip.rb:  48:in `call'
…0.10/lib/action_dispatch/middleware/show_exceptions.rb:  47:in`call'
…ruby/1.8/gems/railties-3.0.10/lib/rails/rack/logger.rb:  13:in `call'
…ed/bundle/ruby/1.8/gems/rack-1.2.5/lib/rack/runtime.rb:  17:in`call'
….0.10/lib/active_support/cache/strategy/local_cache.rb:  72:in `call'
…hared/bundle/ruby/1.8/gems/rack-1.2.5/lib/rack/lock.rb:  13:in`call'
…hared/bundle/ruby/1.8/gems/rack-1.2.5/lib/rack/lock.rb:  13:in `synchronize'
…hared/bundle/ruby/1.8/gems/rack-1.2.5/lib/rack/lock.rb:  13:in`call'
…onpack-3.0.10/lib/action_dispatch/middleware/static.rb:  30:in `call'
…ruby/1.8/gems/railties-3.0.10/lib/rails/application.rb: 168:in`call'
…ruby/1.8/gems/railties-3.0.10/lib/rails/application.rb:  77:in `send'
…ruby/1.8/gems/railties-3.0.10/lib/rails/application.rb:  77:in`method_missing'
…er-3.0.9/lib/phusion_passenger/rack/request_handler.rb:  96:in `process_request'
….0.9/lib/phusion_passenger/abstract_request_handler.rb: 513:in`accept_and_process_next_request'
….0.9/lib/phusion_passenger/abstract_request_handler.rb: 274:in `main_loop'
….0.9/lib/phusion_passenger/rack/application_spawner.rb: 205:in`start_request_handler'
….0.9/lib/phusion_passenger/rack/application_spawner.rb: 170:in `send'
….0.9/lib/phusion_passenger/rack/application_spawner.rb: 170:in`handle_spawn_application'
….8/gems/passenger-3.0.9/lib/phusion_passenger/utils.rb: 479:in `safe_fork'
….0.9/lib/phusion_passenger/rack/application_spawner.rb: 165:in`handle_spawn_application'
…ssenger-3.0.9/lib/phusion_passenger/abstract_server.rb: 357:in `__send__'
…ssenger-3.0.9/lib/phusion_passenger/abstract_server.rb: 357:in `server_main_loop'
…ssenger-3.0.9/lib/phusion_passenger/abstract_server.rb: 206:in`start_synchronously'
…ssenger-3.0.9/lib/phusion_passenger/abstract_server.rb: 180:in `start'
….0.9/lib/phusion_passenger/rack/application_spawner.rb: 128:in`start'
…passenger-3.0.9/lib/phusion_passenger/spawn_manager.rb: 253:in `spawn_rack_application'
….9/lib/phusion_passenger/abstract_server_collection.rb: 132:in`lookup_or_add'
…passenger-3.0.9/lib/phusion_passenger/spawn_manager.rb: 246:in `spawn_rack_application'
….9/lib/phusion_passenger/abstract_server_collection.rb:  82:in`synchronize'
….9/lib/phusion_passenger/abstract_server_collection.rb:  79:in `synchronize'
…passenger-3.0.9/lib/phusion_passenger/spawn_manager.rb: 244:in`spawn_rack_application'
…passenger-3.0.9/lib/phusion_passenger/spawn_manager.rb: 137:in `spawn_application'
…passenger-3.0.9/lib/phusion_passenger/spawn_manager.rb: 275:in`handle_spawn_application'
…ssenger-3.0.9/lib/phusion_passenger/abstract_server.rb: 357:in `__send__'
…ssenger-3.0.9/lib/phusion_passenger/abstract_server.rb: 357:in`server_main_loop'
…ssenger-3.0.9/lib/phusion_passenger/abstract_server.rb: 206:in `start_synchronously'
/var/lib/gems/1.8/gems/passenger-3.0.9/helper-scripts/passenger-spawn-server:99

**Comment by hading** [comment]
The contributorships table has indexes on neither person_id nor contributorship_state_id. I'll add them. 

There is a joint work_id/person_id index - on postgres it's not necessary to index work_id separately in this case, but I don't know how mysql works here. I'd prefer to add the other two, then have you see how this query looks, then only if necessary add work_id.

**Comment by jfurfey** [comment]
I ran the migration and it has made a noticeable difference.
