### ISSUE TITLE
Clicking on Delete a Person generates an error

### ISSUE THREAD

**Issue by ghost** [BibApp/BibApp#11]
When deleting a person I receive the error:

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

My logs are reporting:

NameError (undefined local variable or method `return_path' for #PeopleController:0xbc7d2c8):
  app/controllers/people_controller.rb:32

**Comment by wijiti** [comment]
Apologies. This issue has been addressed recently.
