### ISSUE TITLE
People Import Successful but Error when viewing Person page

### ISSUE THREAD

**Issue by ghost** [BibApp/BibApp#12]
Importing a People CSV using the CSV upload facility works successfully but when I select a person from the People page it generates the "Something Went Wrong" error message and the logs report:

Started GET "/people/12-Rebecca_Furlong" for 180.216.45.224 at Tue May 17 13:14:14 +0000 2011
  Processing by PeopleController#show as HTML
  Parameters: {"id"=>"12-Rebecca_Furlong"}
Rendered people/_admin_actions.html.haml (1.6ms)
Rendered shared/_local_nav.html.haml (1.1ms)
Rendered people/show.html.haml within layouts/application (13.1ms)
Completed   in 34ms

ActionView::Template::Error (undefined method `strip' for nil:NilClass):
    34:         %h3.heading Groups
    35:         = render :partial => 'shared/group_list'
    36:       / ### Hide research focus for inactive people ###
    37:     - if @person.active? and @person.research_focus.strip.length > 0
    38:       #research-focus.span-14
    39:         %h3.heading Research Focus
    40:         %p #{@person.research_focus}
  app/views/people/show.html.haml:37:in`_app_views_people_show_html_haml__491841075_97132490_0'

When importing the CSV the logs report:

Started POST "/people/batch_csv_create" for 180.216.45.224 at Tue May 17 13:11:46 +0000 2011
  Processing by PeopleController#batch_csv_create as HTML
  Parameters: {"person"=>{"import_file"=>#<ActionDispatch::Http::UploadedFile:0xbd11cac @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"person[import_file]\"; filename=\"people.csv\"\r\nContent-Type: text/csv\r\n", @original_filename="people.csv", @tempfile=#<File:/tmp/RackMultipart10394-0>>}, "authenticity_token"=>"l8vlVkS8hrx+vigi37nCXWPRcu7x/+RGFYq9pB9Ut2g=", "utf8"=>"✓"}
Redirected to http://ec2-46-51-138-200.eu-west-1.compute.amazonaws.com/people/batch_csv_show?completed=Your+file+was+accepted+for+processing.+An+email+will+notify+you+when+the+job+is+completed.
Completed 302 Found in 11ms

Started GET "/people/batch_csv_show?completed=Your+file+was+accepted+for+processing.+An+email+will+notify+you+when+the+job+is+completed." for 180.216.45.224 at Tue May 17 13:11:48 +0000 2011
  Processing by PeopleController#batch_csv_show as HTML
  Parameters: {"completed"=>"Your file was accepted for processing. An email will notify you when the job is completed."}
DEPRECATION WARNING: Using form_for(:name, @resource) is deprecated. Please use form_for(@resource, :as => :name) instead. (called from _app_views_people_batch_csv_show_html_haml__471755126_97355850_0 at /home/apache/vhosts/demo.bibapp.openrepository.com/opt/bibapp/app/views/people/batch_csv_show.html.haml:11)
Rendered shared/_header.html.haml (5.4ms)
Rendered shared/_flash_messages.html.haml (0.1ms)
Rendered shared/_footer.html.haml (0.3ms)
Rendered people/batch_csv_show.html.haml within layouts/application (10.6ms)
Completed 200 OK in 17ms (Views: 11.2ms | ActiveRecord: 12.5ms)

If I create a person by hand, the problem does not occur and I can successful load the person's details.

I can provide the CSV if required.

**Comment by hading** [comment]
I believe that wijiti said that this was fixed in master, and I believe that I worked on something related to it that may have fixed it. So I'm going to close this - please reopen if it is in fact not fixed.
