### ISSUE TITLE
Ownership of works I created

### ISSUE THREAD

**Issue by waingram** [BibApp/BibApp#16]
I just added a work to my person, William Ingram (http://connections.ideals.illinois.edu/people/111-William_Ingram), but choosing 'Add Works' from the above URL. I expected the contributorship between me and the work would automatically happen. It didn't.

**Comment by hading** [comment]
So basically if one manually adds a work to a person the work should automatically be verified?

If so, ought to be easy enough to do.

**Comment by waingram** [comment]
Correct. Or if someone adds a batch to a person (which I think already works).

**Comment by hading** [comment]
This is fixed for adding individual works. If both a person and work are defined in WorksController#create then it will go ahead and verify the corresponding contributorship automatically.

I do think this already works for a batch upload to a person. If not that can be another ticket.
