### ISSUE TITLE
Accessing login page results in open_id_presets missing method

### ISSUE THREAD

**Issue by ghost** [BibApp/BibApp#17]
I have updated two bibapp installations to the latest source and both have displayed the error below when attempting to log in. Logging in for the first time proves successful but if anyone else attempts to log in an error is displayed.

Started GET "/login?return_to=%2F" for 180.216.45.224 at Tue May 31 15:52:47 +0000 2011
  Processing by UserSessionsController#new as HTML
  Parameters: {"return_to"=>"/"}
Rendered user_sessions/new.html.haml within layouts/application (3.9ms)
Completed   in 6ms

ActionView::Template::Error (undefined method `open_id_presets' for #<Rails::Application::Configuration:0xaf0aa50>):
    27:     %p
    28:       %h3 Login using external credentials:
    29:       - if Bibapp::Application.config.allow_open_id
    30:         - Bibapp::Application.config.open_id_presets.each do |preset|
    31:           = button_to "Sign in With #{preset['name'].titleize} OpenID", "/auth/open_id?openid_url=#{CGI.escape(preset['id'])}"
    32:           %br/
    33:         = button_to "Sign in With Generic OpenID", '/auth/open_id'
  app/views/user_sessions/new.html.haml:30:in`_app_views_user_sessions_new_html_haml__395553184_105604650_0'

**Comment by hading** [comment]
I should probably set allow_open_id to be false by default in the open_id.rb initializer.

**Comment by hading** [comment]
Set allow_open_id to false by default and added comment about how to turn it back on and configure it.
