### ISSUE TITLE
openURL/SFX problem

### ISSUE THREAD

**Issue by hading** [BibApp/BibApp#21]
(from Wally Grotophorst, George Mason University)

I've been working with a new installation of bibapp, migrating our
existing 1.0 (rails2) installation to a new server with 1.1.1 bibapp
code and rails 3. I pulled over a copy of the 1.0 database and
updated the schema to reflect the 1.1.1 structure. Seems like
everything is working well but OpenURL linking doesn't work.

The problem? On the new (1.1.1-RC3) installation, if I hover over the
"Find It!" link, I see the beginnings of a proper OpenURL (e.g.,
http://sfx.wlrc.org/gm?) but it doesn't contain any info from the
individual citation. Here's all I see:

http://sfx.wrlc.org/gm?ctx_ver=Z39.88-2004

On the same citation from our old (1.0) version, the OpenURL is
correctly formed:

http://sfx.wrlc.org/gm?ctx_ver=Z39.88-2004&rft.date=1986-07-01&rft.issue=&rft.jtitle=NRL+Letter+Report+6120-589&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rft.volume=&rft.atitle=Possible+Toxic+Materials+in+Wind+Tunnel+Exhaust+Targets+Exposed+to+High+Energy+Laser&rft.genre=article&rft.epage=&rft.spage=&rft.au=Cozzens,%20R.%20F.

So, with all that as prelude, I guess my question is something like:
"Why am I not getting the bibliographic elements in the OpenURL under
1.1.1-RC3? I have the _exact_ same $WORK_SUFFIX = value in
personalize.rb on both systems.

If you care to see the problem, here are the servers in question:

original system: http://rpm.gmu.edu
1.1.1-RC3 system: http://rpm2.gmu.edu

Any ideas appreciated.

**Comment by jstirnaman** [comment]
The problem is in the begin/rescue/end block at 152 in app/helpers/application_helper. I think rescue is always returning the coin up to that point and then exiting. I don't understand why it's in there at all.
    # We want AR objects!
    if work.class == Hash
      begin
        work = Work.find(work["pk_i"]).include(:authors)
      rescue
        return coin
      end
    end

**Comment by jstirnaman** [comment]
Now I understand. It's rescuing this: 
undefined method `include' for #JournalArticle:0x106da8f20

**Comment by jstirnaman** [comment]
I don't think we have to explicitly load the :authors scope. It seems to work OK without .include(:authors), like this:
if work.class == Hash
begin
work = Work.find(work["pk_i"])
rescue
return coin
end
end

**Comment by hading** [comment]
I think you're probably right here. But we can - I think the problem here is that I need to interchange the include and the find. I'm going to try that on our branch and see if that fixed it, but that's probably all there is to it, just a mistake I made when refactoring.

**Comment by hading** [comment]
Ah no, my mistake. authors isn't an association of Work, it's a method. As the authors method is now it should only make two database calls, so I'll just try Jason's solution and not bother including anything - it's already doing it as efficiently as it can.

**Comment by hading** [comment]
Commit 2595a8c should fix this, exactly as suggested by jstirnaman.
