### ISSUE TITLE
HTML is escaped in citeproc formatted results

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#28]
http://connections.ideals.illinois.edu/search?utf8=%E2%9C%93&rows=10&sort=created&order=descending&export=apa&q=congressional&fq[]=status%3A3&view=all&page=1&commit=Go#works

What I see: Send search results to a citation format (APA, Chicago, etc.). Browser output displays HTML tags.
What I expect to see: A list of citations formatted in the selected output style.

Output from the Citeproc formatter is getting escaped. Probably needs to be updated for Rails 3.

**Comment by hading** [comment]
Yeah, that doesn't look great. 

It looks like in the shared partial for _works when !@export.blank? we just need to declare @works to be html_safe. Will check and see how that does.

**Comment by hading** [comment]
Fixed in commit 958f11f.

**Comment by hading** [comment]
I should also note that in fixing this issue I noticed that the apa.csl style was hard-coded in WorkExport and that is fixed in commit a3da018e9.
