### ISSUE TITLE
Resumption links not self-closing in RDF-formatted search results 

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#33]
Page resumption links in app/views/search/index.rdf.haml and index.xml.haml do not self-close. Instead, they remain unclosed which violates well-formed XML.
By default in Rails 3 HAML output is HTML5 and does not self-close tags. According to documentation, certain tags including "link" tag are self-closing but this doesn't appear to be the case in Bibapp for some reason. See http://groups.google.com/group/haml/browse_thread/thread/123986888ce41613 and http://haml-lang.com/docs/yardoc/file.HAML_REFERENCE.html#autoclose-option
The simplest solution seems to be to use a custom tag instead of the asset "link" tag. If that's the solution then is there an easy way to override HAML's format on a view-by-view basis or should the rdf and and xml views be coverted to .rxml as in the RSS views, e.g. app/views/people/show.rss.rxml?

**Comment by jstirnaman** [comment]
Another option would be to set Haml default :format to :xhtml instead of HTML5. This applies across the entire application. However, you can still specify HTML5 doctype if you need to by using !!!.
We probably don't want to use a different link tag since that's the standard for Atom and, thus, OpenSearch.

**Comment by hading** [comment]
I'm not sure offhand. If there is no better solution my inclination might be to make anything where this is a problem into an _._.erb. But I'll look into it at some point and see if I can figure out a better solution than that.

**Comment by hading** [comment]
Or if not an erb then a builder or something like that. I'm going to fool around with that and see if I can get something reasonable working that way.

**Comment by hading** [comment]
Redoing the xml view using builder seems to work just fine. I'll try the rdf view as well.

**Comment by hading** [comment]
Incidentally, I prefer this route because I'd prefer to stick with the rails default for the html views, which of course comprise the majority of the views. Rather than fool around with having to set HTML 5 for every HTML view it seems more reasonable to use something explicitly designed for creating XML views to create the less common XML views.

**Comment by hading** [comment]
I should probably try to take care of anything that generated xml right now. To do the rdf mentioned in this issue, for example, involves fixing a partial as well, that may itself be invoked by other views, etc. I should probably just track it all down right now.

**Comment by hading** [comment]
I fixed up all the xml generating views that I could find. People should keep an eye on this for any bugs, as this was a lot of manual work converting the views.
