### ISSUE TITLE
Pen_name creation fails if matches.nil? in contributorship.rb > calculate_inclusion_score

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#35]
Pen_name creation fails if matches in calculate_inclusion_score returns nil.  The AJAX call returns error "ActionView::MissingTemplate (Missing template pen_names/index" and no name_strings are added to the person.

In contributorship.rb, this
  def calculate_inclusion_score(known_ids, possible_ids, max_score)
    logger.debug"Calculate_inclusion_score possible_ids = #{possible_ids.inspect}"
    return 0 if possible_ids.empty?
    known_ids = known_ids.to_set
    matches = possible_ids.detect do |id|
      known_ids.include?(id)
    end
    return ((max_score / possible_ids.size) \* matches.size)
  end

should instead be something like

In contributorship.rb, this
  def calculate_inclusion_score(known_ids, possible_ids, max_score)
    logger.debug"Calculate_inclusion_score possible_ids = #{possible_ids.inspect}"
    return 0 if possible_ids.empty?
    known_ids = known_ids.to_set
    matches = possible_ids.detect do |id|
      known_ids.include?(id)
    end
    return 0 if matches.nil?
    return ((max_score / possible_ids.size) \* matches.size)
  end

Here's the complete development.log: 

==== Params: {"name_string_id"=>"22009", "authenticity_token"=>"dazOX/C36Gx+rr2u635dW0eC+KwrzxyE4FlDlDoopqM=", "action"=>"create", "person_id"=>"705", "controller"=>"pen_names", "_"=>""}

==== reload? nil
  SQL (0.2ms)  BEGIN
  SQL (2.2ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"pen_names"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum

  SQL (0.7ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"pen_names"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum
  PK and serial sequence (36.0ms)   SELECT attr.attname, seq.relname
 FROM pg_class seq,
 pg_attribute attr,
 pg_depend dep,
 pg_namespace name,
 pg_constraint cons
 WHERE seq.oid = dep.objid
 AND seq.relkind = 'S'
 AND attr.attrelid = dep.refobjid
 AND attr.attnum = dep.refobjsubid
 AND attr.attrelid = cons.conrelid
 AND attr.attnum = cons.conkey[1]
 AND cons.contype = 'p'
 AND dep.refobjid = '"pen_names"'::regclass

  SQL (44.1ms)  INSERT INTO "pen_names" ("updated_at", "created_at", "person_id", "name_string_id") VALUES ('2011-08-23 16:10:22.158945', '2011-08-23 16:10:22.158945', 705, 22009) RETURNING "id"
  NameString Load (0.4ms)  SELECT "name_strings".\* FROM "name_strings" WHERE "name_strings"."id" = 22009 LIMIT 1
  SQL (0.7ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"work_name_strings"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum
  WorkNameString Load (162.2ms)  SELECT "work_name_strings".\* FROM "work_name_strings" WHERE ("work_name_strings".name_string_id = 22009)
  SQL (0.6ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"work_name_strings"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum
  Work Load (21.5ms)  SELECT "works".\* FROM "works" WHERE "works"."id" = 12897 LIMIT 1
  SQL (1.0ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"works"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum
  SQL (2.1ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"works"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum

  SQL (1.4ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"contributorships"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum
  Contributorship Load (0.5ms)  SELECT "contributorships".\* FROM "contributorships" WHERE "contributorships"."role" = 'Author' AND "contributorships"."person_id" = 705 AND "contributorships"."work_id" = 12897 AND ("contributorships".pen_name_id = 4939) LIMIT 1
  SQL (0.4ms)  SELECT 1 FROM "contributorships" WHERE "contributorships"."person_id" = 705 AND ("contributorships"."work_id" = 12897) LIMIT 1
  PK and serial sequence (7.5ms)   SELECT attr.attname, seq.relname
 FROM pg_class seq,
 pg_attribute attr,
 pg_depend dep,
 pg_namespace name,
 pg_constraint cons
 WHERE seq.oid = dep.objid
 AND seq.relkind = 'S'
 AND attr.attrelid = dep.refobjid
 AND attr.attnum = dep.refobjsubid
 AND attr.attrelid = cons.conrelid
 AND attr.attnum = cons.conkey[1]
 AND cons.contype = 'p'
 AND dep.refobjid = '"contributorships"'::regclass

  SQL (44.2ms)  INSERT INTO "contributorships" ("created_at", "position", "score", "updated_at", "pen_name_id", "hide", "person_id", "highlight", "contributorship_state_id", "work_id", "role") VALUES ('2011-08-23 16:10:22.566860', NULL, 0, '2011-08-23 16:10:22.566860', 4939, 'f', 705, NULL, 1, 12897, 'Author') RETURNING "id"
  Person Load (0.5ms)  SELECT "people".\* FROM "people" WHERE "people"."id" = 705 LIMIT 1
  Work Load (0.5ms)  SELECT "works".\* FROM "works" WHERE "works"."id" = 12897 LIMIT 1
  SQL (0.2ms)  ROLLBACK
Completed 500 Internal Server Error in 783ms

NoMethodError (You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.size):
  app/models/contributorship.rb:153:in `calculate_inclusion_score'
  app/models/contributorship.rb:143:in`calculate_collaborator_score'
  app/models/contributorship.rb:130:in `calculate_score'
  app/models/contributorship.rb:170:in`calculate_initial_score'
  app/models/pen_name.rb:21:in `set_contributorships'
  app/models/pen_name.rb:18:in`set_contributorships'
  app/controllers/pen_names_controller.rb:41:in `create'

**Comment by hading** [comment]
At first glance it looks to me like it ought never to return nil, but I'll give it a more thorough look.

**Comment by hading** [comment]
Yes. In fact the root of the problem here is that it should be select, not detect.

Fixed in commit 5e0cdca.
