### ISSUE TITLE
Publication name for web pages

### ISSUE THREAD

**Issue by sshreeves** [BibApp/BibApp#39]
When you have a web page as a work, the publication name seems to always be 'unknown' - see http://connections.ideals.illinois.edu/works/18364 - for an example. The publication name should be the same as the title of the web page (as it is for books). I would also suggest we need to rename the web page to website as that is much more common.

Sarah

**Comment by hading** [comment]
None of this sounds difficult. When we get the i18n branch merged it'll be easy to fix labelling (and I may just make this change in that branch).

**Comment by hading** [comment]
Fixed labelling in i18n. I'm not going to do it independently in master - it can wait until i18n is merged in. Still thinking about the publication_name/title problem.

**Comment by hading** [comment]
Okay, setting the publication title wasn't as hard as I feared. In master now.
