### ISSUE TITLE
i18n - user profile language selection use name instead of locale

### ISSUE THREAD

**Issue by cjuergen** [BibApp/BibApp#56]
The language selection in the user profile uses the locales, e.g.
en, de, fr in the select presented to the user. It would be more user friendly to use the language name like it is done in the language switch in the header.

changes in 
app/views/users/edit.html.haml
- ```
     = form.select(:default_locale, I18n.available_locales.collect {|locale| locale.to_s}.sort, :selected => (@user.default_locale || I18n.locale).to_s)
  ```
- ```
     = form.select(:default_locale, I18n.available_locales.collect {|locale| [t('i18n.language.name', :locale => locale), locale.to_s]}.sort, :selected => (@user.default_locale || I18n.locale).to_s)
  ```

app/views/users/new.html.haml
- ```
     = form.select(:default_locale, I18n.available_locales.collect {|locale| locale.to_s}.sort, :selected => I18n.locale.to_s)
  ```
- ```
     = form.select(:default_locale, I18n.available_locales.collect {|locale| [t('i18n.language.name', :locale => locale), locale.to_s]}.sort, :selected => I18n.locale.to_s)
  ```

already submitted to my i18n branch
https://github.com/cjuergen/BibApp/commit/3c96fa8e2b2d3b019af403a81e09932468ca6201

**Comment by hading** [comment]
That's fine with me. I've incorporated your change.
