### ISSUE TITLE
Password forgotten possible on an not yet activated user account

### ISSUE THREAD

**Issue by cjuergen** [BibApp/BibApp#64]
Hi all,

this is a minor issue and independent of the i18n  work.

It is possible to use "Password forgotten" on an not yet activated account. The email with the new password will be send to the user, but using the password will have no effect.
Users do very often (my experience with DSpace) forget to verify their registration and later just use the password forgotten function.

So, in that case using the password forgotten on an inactivated account, the activation code should be sent again and the user informed that the registration has not been completed.

Claudia

**Comment by hading** [comment]
All right. There's some other stuff around passwords that needs work as well.

**Comment by hading** [comment]
Fixed this part of it. If an unactivated user asks for a password reset then there is a flash that says the the account hasn't been activated and the activation link is resent.
