### ISSUE TITLE
Customize the number of returned RDF results

### ISSUE THREAD

**Issue by jfurfey** [BibApp/BibApp#76]
Right now you can only return 100 rows of RDF results.  It would be nice to be able to customize the number of returned results.  This applies to all formats, not just RDF I suppose.

From the Google Group.

http://bibapp.mbl.edu/works?rows=10&sort=created&order=descending&format=rdf 

I would expect the above url to return the 10 most recently created
records in rdf format.  But it returns over a 100.  Is the rows
parameter not what I want here? 

---

[From Jason S.]

John,
Rows is the correct param but in Works#index it's set to only return 100 rows for RDF. I think it will ignore anything in the URL:

 elsif params[:format] == "rdf"
   params[:rows] = 100
   search(params)

**Comment by hading** [comment]
Only use 100 if params[:rows] isn't supplied, i.e. change to ||= here.
