### ISSUE TITLE
Solr refresh_index fails

### ISSUE THREAD

**Issue by simblio** [BibApp/BibApp#78]
We were trying to migrate from our old version to git hub code. Everything goes smooth but when we run 

rake solr:refresh_index RAILS_ENV='production'

it fails.

rake aborted!
undefined method `publication_date_year' for #JournalArticle:0x86a8940

Tasks: TOP => solr:refresh_index

**Comment by hading** [comment]
Have you run the migrations? The missing field was added recently.

RAILS_ENV=production rake db:migrate

Then try to refresh the index again.

**Comment by simblio** [comment]
Yes I did, But still I'm getting the same error, 

RAILS_ENV=production rake db:migrate --trace
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute db:migrate
*\* Invoke db:schema:dump (first_time)
*\* Invoke environment
*\* Execute db:schema:dump

Re-indexing all BibApp Works in Solr...

***\* Depending on the number of works,
***\* this may take a long time.

Start time: Sat Jan 21 13:22:42 +0530 2012
rake aborted!
undefined method `publication_date_year' for #JournalArticle:0x65f74d0

Tasks: TOP => solr:refresh_index

**Comment by hading** [comment]
That's a bit odd then. I assume your db/migrate directory has the following file:

20111111201022_split_publication_date_in_works.rb

which is where that field is defined.  Does the field appear in db/schema.rb? There should be a section that looks like:

create_table "works", :force => true do |t|
    ... (lots of other fields)
    t.string   "location"
    t.integer  "publication_date_year"
    t.integer  "publication_date_month"
    t.integer  "publication_date_day"
  end

**Comment by simblio** [comment]
20111111201022_split_publication_date_in_works.rb file exist, 
but  db/schema.rb got something missing for that table 'works'

this is current "works" table in scheme.rb

create_table "works", :force => true do |t|
    t.string   "type"
    t.text     "title_primary"
    t.text     "title_secondary"
    t.text     "title_tertiary"
    t.text     "affiliation"
    t.string   "volume"
    t.string   "issue"
    t.string   "start_page"
    t.string   "end_page"
    t.text     "abstract"
    t.text     "notes"
    t.text     "links"
    t.integer  "work_state_id"
    t.integer  "work_archive_state_id"
    t.integer  "publication_id"
    t.integer  "publisher_id"
    t.datetime "archived_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "original_data"
    t.integer  "batch_index",              :default => 0
    t.text     "scoring_hash"
    t.date     "publication_date"
    t.string   "language"
    t.text     "copyright_holder"
    t.boolean  "peer_reviewed"
    t.string   "machine_name"
    t.string   "publication_place"
    t.string   "sponsor"
    t.string   "date_range"
    t.string   "identifier"
    t.string   "medium"
    t.string   "degree_level"
    t.string   "discipline"
    t.string   "instrumentation"
    t.text     "admin_definable"
    t.text     "user_definable"
    t.integer  "authority_publication_id"
    t.integer  "authority_publisher_id"
    t.integer  "initial_publication_id"
    t.integer  "initial_publisher_id"
    t.string   "location"
  end

**Comment by hading** [comment]
Can you tell me what database you're running and what OS you're on? I'll need to think a bit more about what to do, but that information will help. We'll probably need to extract some information about the current state of the database to figure out why it doesn't seem to be running that migration properly.

**Comment by simblio** [comment]
It's running with PostgreSQL 8.4 and OS is Ubuntu Linux 10.04.3. We are running without rvm and using ruby Enterprise Edition. 

## I tried to update the db/scheme.rb and run migration, but the file just changed to the old state and no migration happened.

**Comment by hading** [comment]
Could you email me (hding2@illinois.edu) the following (as attachments, not inline):
- The current db/schema.rb file
- the results of ls on the db/migrate directory
- the results you get by doing the following:
  RAILS_ENV=production rails dbconsole
  select \* from schema_migrations order by version asc;
- a dump of your current database schema, e.g. by (you may have to supply username/password etc.)
  pg_dump --schema-only (dbname)

I'll see if there are any clues in there. 

And just to confirm - you're doing everything in the Rails production environment, i.e. with RAILS_ENV set to production?

**Comment by hading** [comment]
Oh, also what version of Bibapp do you have? The current master or a tagged release?

**Comment by simblio** [comment]
This issue was resolved with the great help of 'hading'

Issue was, some migrations haven't been really been run, although the schema migrations table shows them as having been run.

Solution was

``` bash
# Opening Rails Database Console
RAILS_ENV=production budle exec rails dbconsole

# Deleting migartion number
# If Migration is '20110414150835_add_user_id_to_person.rb'
# Then migration_number is 20110414150835
delete from schema_migrations where version='migration_number_here';

# Quit db console by \q

# Running that specific migration again
# Make sure your solr is running by RAILS_ENV=production rake solr:start
RAILS_ENV=production rake db:migrate:up VERSION=migration_number_here

```

I express my sincere thanks to 'hading', without his help this could never resolved.
Cheers to BibApp Team

## Current Working version is public at [http://yuj.cusat.ac.in](http://yuj.cusat.ac.in)
