### ISSUE TITLE
gbsclasses.js not loaded in works#index or works#show

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#79]
Book thumbnails aren't displaying in the latest version of master. There's no script tag for gbsclasses.js linked in works#index or works#show. 'gbsclasses' is not included in views/layouts/application.html.haml and I can't find it included in any other views.

**Comment by hading** [comment]
I'll look at it. It might have gotten deleted as I moved the javascript from prototype to jquery.

**Comment by hading** [comment]
I put it back in the application layout. I'm pretty sure I accidentally took it out when purging the prototype code.
