### ISSUE TITLE
Javascript toggles for collapsible groups not working in /memberships/new

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#82]
Seem to be problems with public/javascripts/specific/memberships/_group_list.js 
Result is that toggle fails on group names in /memberships#new 
Possible problems.
*1 Line 3 toggle_folder(this): this seems to be returning the value of the href and not the element itself. Error returned for toggle_folder is "Uncaught TypeError: Object javascript:void(0) has no method 'readAttribute'".
*2 I think for JQuery the method in line 13 should be e.attr instead of e.readAttribute.

Jason

**Comment by jstirnaman** [comment]
Ignore for now. Turns out I was missing some of the specific/ js files so this is probably my fault.

**Comment by jfurfey** [comment]
I'm pretty sure I have all of the specific javascript files and this function is nor working for me.  Is this working for you now Jason?

**Comment by jstirnaman** [comment]
OK. I think I've solved it. First, readAttribute() should be changed to .attr().  Second, e.attr() should be changed to $(e).attr(). I'll send a pull request soon for my change.

**Comment by jstirnaman** [comment]
Here's my fix: https://github.com/jstirnaman/BibApp/commit/5f17098080252ea139858fe0c2efb05807a23249
It hasn't been pulled into BibApp/master yet, though.

**Comment by hading** [comment]
Sorry, perhaps I missed this when doing the jquery conversion. I'll try to pull your change in soon.

**Comment by hading** [comment]
All right, this is in master now. Thanks for the catch.

**Comment by jstirnaman** [comment]
Sure. Thanks.

----- Reply message -----
From: "Howard Ding" reply@reply.github.com
To: "Jason Stirnaman" stirnamanj@gmail.com
Subject: [BibApp] Javascript toggles for collapsible groups not working in /memberships/new (#82)
Date: Wed, Feb 8, 2012 11:26 am

All right, this is in master now. Thanks for the catch.

---
