### ISSUE TITLE
Sorting issue with lowercase

### ISSUE THREAD

**Issue by jfurfey** [BibApp/BibApp#84]
If work titles begin with lowercase letters, they are not sorted by alpha correctly.  They just wind at the beginning of the list.  Same goes for last names of authors.

**Comment by hading** [comment]
I'm not surprised. I should be able to fix this without much difficulty. I think.

**Comment by hading** [comment]
Actually it'd be quite helpful (if you don't mind) if you could provide specific views (i.e. urls) where you find this happening. (No doubt that it is - just easier for me to fix them if I know where they are rather than by combing through the code.)

**Comment by hading** [comment]
I think that what I did with stopwords (creating a sort_name field) should solve this. If it doesn't (or if there are views where it doesn't) then please open another issue about it.
