### ISSUE TITLE
i18n - roles for creators and contributors

### ISSUE THREAD

**Issue by cjuergen** [BibApp/BibApp#86]
The roles for creators and contributors in the work display are not i18n
app/views/works/metadata/

_contributors.html.haml
line 3:     %td.label #{role}(s):
_creators.html.haml 
line 4:     %td.label #{@work.creator_role}(s):

The roles themselves are already in the language catalogue.

Claudia Jürgen

**Comment by hading** [comment]
Looks trivial. I'll see if I can get it today.

**Comment by hading** [comment]
This should be okay now.
