### ISSUE TITLE
Import fails if machine_name already exists in table.name_strings

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#9]
The problem seems to be around https://github.com/BibApp/BibApp/blob/master/app/models/import.rb#L217 or in citationimporter plugin.
An import that should otherwise be successful fails because a name_string already has a matching machine_name. Instead, it should move on and continue importing the citation.

**Comment by jstirnaman** [comment]
Here's the UI output:
Errors
"Import error:<em>IKKβ phosphorylation regulates RPS3 nuclear translocation and NF-κB function during infection with Escherichia coli strain O157:H7</em> could not be imported. PGError: ERROR: duplicate key value violates unique constraint "machine_name" : INSERT INTO "name_strings" ("machine_name", "updated_at", "created_at", "name", "cleaned") VALUES ('wan fengyi', '2011-03-30 15:02:03.472209', '2011-03-30 15:02:03.472209', 'Wan,Fengyi', 'f') RETURNING "id"<br/>"

Matched 0 works Everything matches.

And the log output:
==== Starting Batch Import ==== 

  ImportFile Load (23.8ms)  SELECT "attachments".\* FROM "attachments" WHERE "attachments"."type" = 'ImportFile' AND ("attachments".asset_id = 1359 AND "attachments".asset_type = 'Import') LIMIT 1
- This file is RIS format.

Parsing...

Successfully parsed 1 citations using: RisParser!

Parsed Citations: 1

Attempting to import 1 citations...

Generating attribute hash from parsed citation...

Trying to parse date: 2011/04//...
Date parsed as: 2011-01-01

Successfully generated attribute hash!

Successfully imported 1 citations!

1 Attr Hashes: [{:links=>#<ActiveSupport::Multibyte::Chars:0x10671d930 @wrapped_string="http://www.ncbi.nlm.nih.gov/pubmed/21399639">, :identifier=>#<ActiveSupport::Multibyte::Chars:0x10671d390 @wrapped_string="1718">, :publication_date=>"2011-01-01", :start_page=>#<ActiveSupport::Multibyte::Chars:0x10671ccb0 @wrapped_string="335">, :abstract=>#<ActiveSupport::Multibyte::Chars:0x10671c7d8 @wrapped_string="NF-κB is a major gene regulator in immune responses, and ribosomal protein S3 (RPS3) is an NF-κB subunit that directs specific gene transcription. However, it is unknown how nuclear translocation of RPS3 is regulated. Here we report that phosphorylation of RPS3 Ser209 by the kinase IKKβ was crucial for nuclear localization of RPS3 in response to activating stimuli. Moreover, virulence protein NleH1 of the foodborne pathogen Escherichia coli strain O157:H7 specifically inhibited phosphorylation of RPS3 Ser209 and blocked RPS3 function, thereby promoting bacterial colonization and diarrhea but resulting in less mortality in a gnotobiotic piglet-infection model. Thus, the IKKβ-dependent modification of a specific amino acid in RPS3 promoted specific NF-κB functions that underlie the molecular pathogenetic mechanisms of E. coli O157:H7.">, :volume=>#<ActiveSupport::Multibyte::Chars:0x10671c210 @wrapped_string="12">, :title_primary=>#<ActiveSupport::Multibyte::Chars:0x10671bb08 @wrapped_string="IKKβ phosphorylation regulates RPS3 nuclear translocation and NF-κB function during infection with Escherichia coli strain O157:H7">, :work_name_strings=>[{:role=>"Author", :name=>#<ActiveSupport::Multibyte::Chars:0x10673f288 @wrapped_string="Wan,Fengyi">}, {:role=>"Author", :name=>#<ActiveSupport::Multibyte::Chars:0x10673d2d0 @wrapped_string="Weaver,Amanda">}, {:role=>"Author", :name=>#<ActiveSupport::Multibyte::Chars:0x10673a5f8 @wrapped_string="Gao,Xiaofei">}, {:role=>"Author", :name=>#<ActiveSupport::Multibyte::Chars:0x106738708 @wrapped_string="Bern,Michael">}, {:role=>"Author", :name=>#<ActiveSupport::Multibyte::Chars:0x106737588 @wrapped_string="Hardwidge,Philip R">}, {:role=>"Author", :name=>#<ActiveSupport::Multibyte::Chars:0x106736228 @wrapped_string="Lenardo,Michael J">}], :notes=>#<ActiveSupport::Multibyte::Chars:0x10671af00 @wrapped_string="10.1038/ni.2007">, :klass=>#<ActiveSupport::Multibyte::Chars:0x10671a8c0 @wrapped_string="JournalArticle">, :issue=>#<ActiveSupport::Multibyte::Chars:0x10671a398 @wrapped_string="4">, :original_data=>"TY  - JOUR\n\nID  - 1718\n\nT1  - IKKβ phosphorylation regulates RPS3 nuclear translocation and NF-κB function during infection with Escherichia coli strain O157:H7\n\nJF  - Nature Immunology\n\nJA  - Nat. Immunol\n\nM3  - 10.1038/ni.2007\n\nA1  - Wan,Fengyi\n\nA1  - Weaver,Amanda\n\nA1  - Gao,Xiaofei\n\nA1  - Bern,Michael\n\nA1  - Hardwidge,Philip R\n\nA1  - Lenardo,Michael J\n\nVL  - 12\n\nIS  - 4\n\nPY  - 2011/04//\n\nN2  - NF-κB is a major gene regulator in immune responses, and ribosomal protein S3 (RPS3) is an NF-κB subunit that directs specific gene transcription. However, it is unknown how nuclear translocation of RPS3 is regulated. Here we report that phosphorylation of RPS3 Ser209 by the kinase IKKβ was crucial for nuclear localization of RPS3 in response to activating stimuli. Moreover, virulence protein NleH1 of the foodborne pathogen Escherichia coli strain O157:H7 specifically inhibited phosphorylation of RPS3 Ser209 and blocked RPS3 function, thereby promoting bacterial colonization and diarrhea but resulting in less mortality in a gnotobiotic piglet-infection model. Thus, the IKKβ-dependent modification of a specific amino acid in RPS3 promoted specific NF-κB functions that underlie the molecular pathogenetic mechanisms of E. coli O157:H7.\n\nSP  - 335\n\nEP  - 343\n\nSN  - 1529-2916\n\nUR  - http://www.ncbi.nlm.nih.gov/pubmed/21399639\n\n", :publication=>["Nat. Immunol", "Nature Immunology"], :issn_isbn=>#<ActiveSupport::Multibyte::Chars:0x106719ad8 @wrapped_string="1529-2916">, :end_page=>#<ActiveSupport::Multibyte::Chars:0x106719498 @wrapped_string="343">}]

===SET PUBLICATION INFO===

  Publisher Load (27.6ms)  SELECT "publishers".\* FROM "publishers" WHERE "publishers"."name" = 'Unknown' LIMIT 1
  Publisher Load (8.5ms)  SELECT "publishers".\* FROM "publishers" WHERE "publishers"."id" = 395 LIMIT 1
  Publication Load (57.0ms)  SELECT "publications".\* FROM "publications" WHERE "publications"."name" IN ('Nat. Immunol', 'Nature Immunology') AND "publications"."issn_isbn" = '1529-2916' AND "publications"."initial_publisher_id" = 395 LIMIT 1
  SQL (0.1ms)  BEGIN

Pub: 8346 | Auth: 8346

  Identifier Load (26.9ms)  SELECT "identifiers".\* FROM "identifiers" WHERE "identifiers"."type" = 'ISSN' AND "identifiers"."name" = '15292916' LIMIT 1
  Identifier Load (40.2ms)  SELECT "identifiers".*, "identifiers"."id" FROM "identifiers" INNER JOIN "identifyings" ON "identifiers".id = "identifyings".identifier_id WHERE "identifiers"."id" = 3186 AND (("identifyings".identifiable_id = 8346) AND ("identifyings".identifiable_type = 'Publication')) LIMIT 1

 === AFTER-SAVE IN INDEX OBSERVER ===

  SQL (0.2ms)  COMMIT
  Publication Load (0.6ms)  SELECT "publications".\* FROM "publications" WHERE "publications"."id" = 8346 LIMIT 1
  SQL (0.1ms)  BEGIN
  SQL (0.2ms)  ROLLBACK
  SQL (0.1ms)  BEGIN
  SQL (0.2ms)  ROLLBACK
  SQL (0.1ms)  BEGIN
  Publication Load (0.5ms)  SELECT "publications".\* FROM "publications" WHERE "publications"."id" = 8346 LIMIT 1
  Keywording Load (23.9ms)  SELECT DISTINCT "keywordings".keyword_id FROM "keywordings" WHERE ("keywordings".work_id = NULL)

===DEDUPLICATE===

Duplicates: 0
  SQL (182.6ms)  INSERT INTO "works" ("links", "language", "publication_id", "copyright_holder", "sponsor", "publication_date", "scoring_hash", "machine_name", "user_definable", "end_page", "authority_publication_id", "work_archive_state_id", "issue", "volume", "medium", "identifier", "degree_level", "work_state_id", "abstract", "original_data", "batch_index", "admin_definable", "affiliation", "archived_at", "peer_reviewed", "authority_publisher_id", "updated_at", "title_secondary", "location", "type", "title_tertiary", "notes", "publisher_id", "discipline", "initial_publisher_id", "date_range", "created_at", "initial_publication_id", "title_primary", "start_page", "instrumentation", "publication_place") VALUES ('http://www.ncbi.nlm.nih.gov/pubmed/21399639', NULL, 8346, NULL, NULL, '2011-01-01', '--- 
:collaborator_ids: []

:keyword_ids: []

:publication_id: 8346
:year: 2011
', 'ikkβ phosphorylation regulates rps3 nuclear translocation and nf κb function during infection with escherichia coli strain o157 h7', NULL, '343', NULL, 1, '4', '12', NULL, '1718', NULL, 3, 'NF-κB is a major gene regulator in immune responses, and ribosomal protein S3 (RPS3) is an NF-κB subunit that directs specific gene transcription. However, it is unknown how nuclear translocation of RPS3 is regulated. Here we report that phosphorylation of RPS3 Ser209 by the kinase IKKβ was crucial for nuclear localization of RPS3 in response to activating stimuli. Moreover, virulence protein NleH1 of the foodborne pathogen Escherichia coli strain O157:H7 specifically inhibited phosphorylation of RPS3 Ser209 and blocked RPS3 function, thereby promoting bacterial colonization and diarrhea but resulting in less mortality in a gnotobiotic piglet-infection model. Thus, the IKKβ-dependent modification of a specific amino acid in RPS3 promoted specific NF-κB functions that underlie the molecular pathogenetic mechanisms of E. coli O157:H7.', 'TY - JOUR

ID - 1718

T1 - IKKβ phosphorylation regulates RPS3 nuclear translocation and NF-κB function during infection with Escherichia coli strain O157:H7

JF - Nature Immunology

JA - Nat. Immunol

M3 - 10.1038/ni.2007

A1 - Wan,Fengyi

A1 - Weaver,Amanda

A1 - Gao,Xiaofei

A1 - Bern,Michael

A1 - Hardwidge,Philip R

A1 - Lenardo,Michael J

VL - 12

IS - 4

PY - 2011/04//

N2 - NF-κB is a major gene regulator in immune responses, and ribosomal protein S3 (RPS3) is an NF-κB subunit that directs specific gene transcription. However, it is unknown how nuclear translocation of RPS3 is regulated. Here we report that phosphorylation of RPS3 Ser209 by the kinase IKKβ was crucial for nuclear localization of RPS3 in response to activating stimuli. Moreover, virulence protein NleH1 of the foodborne pathogen Escherichia coli strain O157:H7 specifically inhibited phosphorylation of RPS3 Ser209 and blocked RPS3 function, thereby promoting bacterial colonization and diarrhea but resulting in less mortality in a gnotobiotic piglet-infection model. Thus, the IKKβ-dependent modification of a specific amino acid in RPS3 promoted specific NF-κB functions that underlie the molecular pathogenetic mechanisms of E. coli O157:H7.

SP - 335

EP - 343

SN - 1529-2916

UR - http://www.ncbi.nlm.nih.gov/pubmed/21399639

', 0, NULL, NULL, NULL, NULL, NULL, '2011-03-31 22:04:45.347747', NULL, NULL, 'JournalArticle', NULL, '10.1038/ni.2007', 395, NULL, 395, NULL, '2011-03-31 22:04:45.347747', 8346, 'IKKβ phosphorylation regulates RPS3 nuclear translocation and NF-κB function during infection with Escherichia coli strain O157:H7', '335', NULL, NULL) RETURNING "id"
  Keyword Load (21.8ms)  SELECT "keywords".\* FROM "keywords" INNER JOIN "keywordings" ON "keywords".id = "keywordings".keyword_id WHERE (("keywordings".work_id = 23120))
  Keywording Load (0.6ms)  SELECT "keywordings".\* FROM "keywordings" WHERE ("keywordings".work_id = NULL)
  NameString Load (27.3ms)  SELECT "name_strings".\* FROM "name_strings" WHERE "name_strings"."name" = 'Wan,Fengyi' AND "name_strings"."machine_name" = 'wan fengyi' LIMIT 1
  SQL (36.7ms)  INSERT INTO "name_strings" ("name", "machine_name", "updated_at", "cleaned", "created_at") VALUES ('Wan,Fengyi', 'wan fengyi', '2011-03-31 22:04:45.588479', 'f', '2011-03-31 22:04:45.588479') RETURNING "id"
PGError: ERROR:  duplicate key value violates unique constraint "machine_name"
: INSERT INTO "name_strings" ("name", "machine_name", "updated_at", "cleaned", "created_at") VALUES ('Wan,Fengyi', 'wan fengyi', '2011-03-31 22:04:45.588479', 'f', '2011-03-31 22:04:45.588479') RETURNING "id"
  SQL (0.3ms)  ROLLBACK
  Work Load (20.2ms)  SELECT "works".\* FROM "works" WHERE "works"."batch_index" = 1
  SQL (0.4ms)  BEGIN
  AREL (0.4ms)  UPDATE "imports" SET "works_added" = '--- []

', "updated_at" = '2011-03-31 22:04:48.899878', "import_errors" = '--- 
:import_error: 
- "<em>IKK\xCE\xB2 phosphorylation regulates RPS3 nuclear translocation and NF-\xCE\xBAB function during infection with Escherichia coli strain O157:H7</em> could not be imported. PGError: ERROR: duplicate key value violates unique constraint \"machine_name\"\n\
  : INSERT INTO \"name_strings\" (\"name\", \"machine_name\", \"updated_at\", \"cleaned\", \"created_at\") VALUES (''Wan,Fengyi'', ''wan fengyi'', ''2011-03-31 22:04:45.588479'', ''f'', ''2011-03-31 22:04:45.588479'') RETURNING \"id\"<br/>"
  ' WHERE "imports"."id" = 1359
  SQL (0.6ms)  COMMIT
  SQL (0.1ms)  BEGIN
  AREL (0.3ms)  UPDATE "imports" SET "state" = 'reviewable', "works_added" = '--- []

', "updated_at" = '2011-03-31 22:04:48.903881', "import_errors" = '--- 
:import_error: 
- "<em>IKK\xCE\xB2 phosphorylation regulates RPS3 nuclear translocation and NF-\xCE\xBAB function during infection with Escherichia coli strain O157:H7</em> could not be imported. PGError: ERROR: duplicate key value violates unique constraint \"machine_name\"\n\
  : INSERT INTO \"name_strings\" (\"name\", \"machine_name\", \"updated_at\", \"cleaned\", \"created_at\") VALUES (''Wan,Fengyi'', ''wan fengyi'', ''2011-03-31 22:04:45.588479'', ''f'', ''2011-03-31 22:04:45.588479'') RETURNING \"id\"<br/>"
  ' WHERE "imports"."id" = 1359
  SQL (0.5ms)  COMMIT

**Comment by hading** [comment]
Thanks. I think we've been seeing this here too, so I'll see if I can get it fixed up promptly.

**Comment by hading** [comment]
So the behavior here should be that if a NameString already exists with this machine_name then we ignore the error and (if appropriate) use the existing NameString?

I think where this is actually going wrong is in Work#update_work_name_strings. That method does a find_or_create on NameStrings by machine_name and name, but the uniqueness constraint in the DB is on machine_name only. I'll need to look at the rails-2 code to see what I did here to break this, but I expect it will be an easy fix.

**Comment by hading** [comment]
I'm almost certain that this is the problem here. The previous code just looked up by machine_name. It may be that reverting it to just find_or_create_by_machine_name will do the trick and that's certainly worth trying first.

**Comment by jstirnaman** [comment]
I think that's fine unless there's a case where significantly
different name_strings would end up having the same machine_name.  I'm
guessing that's probably why the lookup was the way it was? I can't
think of a case where that would happen.

On Thu, Apr 7, 2011 at 4:38 PM, hading
reply@reply.github.com
wrote:

**Comment by hading** [comment]
I think that's right. I've changed it back. Let me know if this fixes the problem for you, or if it does just close this ticket. I'll also see if it fixes it for our people here.

**Comment by hading** [comment]
This seems to have fixed things here at UIUC, so I'm closing it.
