### ISSUE TITLE
Strip line breaks from RIS abstracts

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#92]
Steps to reproduce:
1. In PubMed, find a citation that (violating the NLM journal schema) contains line breaks in the abstract, e.g. http://www.ncbi.nlm.nih.gov/pubmed/21969284
2. "Send to" > File > MEDLINE
3. The resultant output will import successfully to BibApp as it passes through the Medline importer which strips line breaks before going to Solr. However, if the same output is passed first to Zotero and exported as RIS and the RIS is then imported into BibApp, the import will fail with an error like
    Import error:<em>Hyperosmolar dextrose injection for recalcitrant Osgood Schlatter disease</em> could not be imported.    400 "ERROR: [doc=Work-27729] multiple values encountered for non multiValued field abstract: [OBJECTIVE , , , , 

ris_importer.rb does not perform the equivalent of medline_importer.rb's strip_line_breaks() on any fields.

Is there any reason why strip_line_breaks() and remove_trailing_period() shouldn't be moved to base_importer.rb?

**Comment by hading** [comment]
Most likely this happened to fix a bug that was seen but it was overlooked to see if there were corresponding bugs in the other importers. I'll see how we might implement this more widely.

Also note that strip_line_breaks (as implemented in medline_importer.rb) is essentially equivalent to the Rails built-in 'squish'. (The latter also strips leading and trailing whitespace, but hey, even better.)

**Comment by hading** [comment]
I've done some general cleanup on the importers first. Now I've gotten Jason's example and am working on reproducing and fixing it.

**Comment by hading** [comment]
Well, adding a value translator for the abstract got me a _different_ error - can't clone nil class.

Unfortunately this error happens during delayed job processing, so it's going to be annoying to track down. But to it, I guess.

**Comment by hading** [comment]
Okay, I think I've been too aggressive in my refactoring. I'm going to go back to master and just try to do what is needed to fix this problem, and then perhaps do some refactoring while testing each time.

**Comment by hading** [comment]
To add to the fun I'm getting an error now when trying to do a refworks-xml import, which is really odd since I don't think I've done anything that should affect that.

On the plus side, adding a value translator to the ris_importer does seem to fix that side of things. So now I need to figure out what's up with the refworks-xml importer.

**Comment by hading** [comment]
It seems still to be parsing the refworks xml properly, but an error is occuring somewhere later in the process. The specific error is:

 <em>Test New Import AASM 2</em> could not be imported. You have a nil object when you didn''t expect it!
 You might have expected an instance of Array.
 The error occurred while evaluating nil.first<br/>

**Comment by hading** [comment]
I think I've done something in Work itself that is causing a problem when we try to create from hash, but I haven't tracked it down yet.

**Comment by hading** [comment]
Trying to bracket the problem in update_from_hash.

**Comment by hading** [comment]
The error occurs in set_publication_info

**Comment by hading** [comment]
And then in set_publisher_from_name

**Comment by hading** [comment]
Then in set_initial_publisher, it seems, alhtough I'm not sure how it could happen there. Well, run it and see.

**Comment by hading** [comment]
I must have made a mistake somewhere earlier - retracing.

**Comment by hading** [comment]
Okay, the error is actually in set_publication_from_name called from set_publication_info. It looks like it's failing on Publication.find_or_create_by_name_and_initial_publisher_id, although I'm not sure how that could be going wrong here either.

**Comment by hading** [comment]
Okay, now I am baffled. The logs show my message before executing this statement but not the one from after. If I get the data with which it is trying to execute this statement then I can do it perfectly well in the console. 

Ah, but then I destroyed that publication and did the attempted to create again and I _did_ get the error I'm ultimately seeing.
The error is occurring in PublicationsSweeper, which would explain why it is just now coming about.

**Comment by hading** [comment]
Okay, that was it. Just another of the dangers of caching!

**Comment by hading** [comment]
Continuing this I'm going to go ahead and try some more of the original refactorings that I wanted to do for importers. Then I'll test them out and see if the three imports still work as expected.

**Comment by hading** [comment]
This works with the data I've tested it on.

To record my confusion: Hash.new(obj) makes obj the default value for the Hash, so that is what is going on in the importers - they're taking a default lambda for the value_importers.
