### ISSUE TITLE
Pin Paperclip to 2.7 for Ruby 1.8.x

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#99]
Specify Paperclip 2.7 in Gemfile.
Latest Paperclip now requires Ruby 1.9.2:
https://github.com/thoughtbot/paperclip/commit/8e80310c27e3e98a12aa3905a850b440dc69705f

**Comment by hading** [comment]
All right, no problem to do this.

At some point Bibapp will work with (probably even require) Ruby 1.9.2. Work on that is likely to start once we have some server upgrades in place here that'll make it easier to move ruby versions.
